const questions = [
  "If you had 3 bullets, which 3 people would you use them on?",
  "Tell me about your earliest childhood memory.",
  "Who is / was your idol?",
  "Who is your celebrity crush?",
  "If you could be any animal for a day, which one would you be?",
  "What 3 adjectives describe your personality?",
  "Do you prefer the daytime or the night?",
  "Which country would you most like to visit?",
  "What's your favourite traditional Spanish food?",
  "What's your favourite international food?",
  "If you could be invisible for a day, what would you do?",
  "Pineapple on pizza, discuss.",
  "What's the best type of cheese?",
  "What is the sexiest and least sexy name?",
  "What's the weirdest smell you have ever smelled?",
  "If animals could talk, which would be the rudest?",
  "Where is the strangest place you've urinated?",
  "How many chickens would it take to kill an elephant?",
  "What is the most embarrassing thing you have ever worn?",
  "What is the strangest thing you have seen in someone else's home?",
  "What would be the worst thing for the government to make illegal?",
  "Who would play you in a film about your life?",
  "If you were arrested with no explanation, what would your friends and family assume you had done?",
  "If you were transported 400 years into the past with no clothes or anything else, how would you prove that you were from the future?",
  "Where was the most inappropriate place you've ever farted?",
  "What is the strangest dream you have ever had?",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
];

export {questions};