const questions = [
  "If you had 3 bullets, which 3 people would you use them on?",
  "Tell me about your earliest childhood memory.",
  "Who is / was your idol?",
  "Who is your celebrity crush?",
  "If you could be any animal for a day, which one would you be?",
  "What 3 adjectives describe your personality?",
  "Do you prefer the daytime or the night?",
  "Which country would you most like to visit?",
  "What's your favourite traditional Spanish food?",
  "What's your favourite international food?",
  "If you could be invisible for a day, what would you do?",
  "Pineapple on pizza, discuss.",
  "What's the best type of cheese?",
  "What is the sexiest and least sexy name?",
  "What's the weirdest smell you have ever smelled?",
  "If animals could talk, which would be the rudest?",
  "Where is the strangest place you've urinated?",
  "How many chickens would it take to kill an elephant?",
  "What is the most embarrassing thing you have ever worn?",
  "What is the strangest thing you have seen in someone else's home?",
  "What would be the worst thing for the government to make illegal?",
  "Who would play you in a film about your life?",
  "If you were arrested with no explanation, what would your friends and family assume you had done?",
  "If you were transported 400 years into the past with no clothes or anything else, how would you prove that you were from the future?",
  "Where was the most inappropriate place you've ever farted?",
  "What is the strangest dream you have ever had?",
  "If you could have one superpower, what would you choose?",
  "What 3 things do you always have in your fridge?",
  "What is the longest you have gone without sleep?",
  "If you had to eat one meal for the rest of your life, what would it be and why?",
  "Would you rather go back in time or be transported to the future?",
  "If you had a time machine and could go back in time, what would you change in history?",
  "If you could have dinner with any person, alive or dead, who would it be?",
  "If you created your own country, what would it be called?",
  "If you were a vegetable, what would you be?",
  "What is your favorite midnight snack?",
  "What is the last TV show that you binge-watched?",
  "What is your favorite ice cream flavour?",
  "Which cartoon character do you wish was real?",
  "How old were you when you learned that Santa does not exist?",
  "If you had to delete all but 3 apps from your smartphone, which ones would you keep?",
  "What would your dream house be like?",
  "Are you a cat person or a dog person?",
  "What is the best thing in your town / city?",
  "What is the best gift you've ever given?  and received?",
  "If you could have a meal with 4 people, who would they be?",
  "Would you rather have good looks but no intelligence or be ugly but intelligent?",
  "What's the best family recipe you have?",
  "If you had a warning label, what would it say?",
  "Who was your first crush?",
  "When was the fist moment you realised you were an adult?",
  "If one of your parents were the President, what would be their first law?",
  "What would be your slogan if you ran for President?",
  "What is the most awkward date you have ever been on?",
  "Have you ever met a real person with an unfortunate name?",
  "Who is your craziest / most interesting relative?",
  "Tell us a funny pick up line that works for you",
  "Tell us a website / series you're embarrassed to admit you love?"
];

export {questions};